export const mentorSkills = [
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "Ruby",
  "Swift",
  "Kotlin",
  "Go",
  "PHP",
  "SQL",
  "NoSQL",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Spring Boot",
  "Ruby on Rails",
  "ASP.NET",
  "Laravel",
  "TensorFlow",
  "PyTorch",
  "Machine Learning",
  "Deep Learning",
  "Data Science",
  "Big Data",
  "Hadoop",
  "Spark",
  "AWS",
  "Azure",
  "Google Cloud",
  "DevOps",
  "CI/CD",
  "Docker",
  "Kubernetes",
  "Microservices",
  "Blockchain",
  "Smart Contracts",
  "Solidity",
  "Cybersecurity",
  "Penetration Testing",
  "Ethical Hacking",
  "Cryptography",
  "Networking",
  "System Administration",
  "Linux",
  "Unix",
  "Windows Server",
  "Agile",
  "Scrum",
  "Kanban",
  "Project Management",
  "Product Management",
  "UI/UX Design",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Graphic Design",
  "Photoshop",
  "Illustrator",
  "Video Editing",
  "Final Cut Pro",
  "Premiere Pro",
  "Content Writing",
  "SEO",
  "Digital Marketing",
  "Social Media Marketing",
  "Google Analytics",
  "Salesforce",
  "Customer Relationship Management (CRM)",
  "Business Analysis",
  "Financial Analysis",
  "Data Analysis",
  "Excel",
  "Power BI",
  "Tableau",
  "R Programming",
  "MATLAB",
  "SAS",
  "STATA",
  "Econometrics",
  "Statistics",
  "Quantitative Research",
  "Qualitative Research",
  "Public Speaking",
  "Negotiation",
  "Leadership",
  "Team Management",
  "Conflict Resolution",
  "Time Management",
  "Career Development",
  "Interview Preparation",
  "Resume Writing",
  "Job Search Strategies",
  "Personal Branding",
  "Entrepreneurship",
  "Startup Development",
  "Fundraising",
  "Venture Capital",
  "Business Strategy",
  "Market Research",
  "Competitive Analysis",
  "Legal Compliance",
  "Intellectual Property",
  "Contract Negotiation",
  "Mergers & Acquisitions",
  "Supply Chain Management",
  "Operations Management",
  "Human Resources",
  "Recruitment",
  "Employee Engagement",
  "Training & Development",
  "Corporate Culture",
  "Diversity & Inclusion",
  "Work-Life Balance",
  "Mentorship",
  "Coaching",
  "Peer Support",
  "Emotional Intelligence",
  "Stress Management",
  "Mindfulness",
  "Workplace Ethics",
  "Sustainability",
  "Corporate Social Responsibility (CSR)",
]
